spring:
  application:
    name: ikeda-operational-ms
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ikeda-operational-ms
      username: configserver
      password: '123456GHJKLMN'